# Generated by Django 4.2.10 on 2024-05-08 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofiles', '0008_alter_userprofile_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=255)),
                ('header_img', models.URLField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('tags', models.TextField()),
                ('course_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofiles.institution')),
            ],
        ),
    ]
