# Generated by Django 4.2.10 on 2024-05-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
