# Generated by Django 4.2.10 on 2024-05-08 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_auto_20240505_1020'),
        ('courses', '0003_alter_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='offered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofiles.institution'),
        ),
    ]
