# Generated by Django 4.2.10 on 2024-05-05 10:18

from django.db import migrations
from django.core.management import call_command


def load_initial_data(apps, schema_editor):
    call_command(
        "loaddata",
        "country.json",
        app_label="userprofiles",
    )


def unload_initial_data(apps, schema_editor):
    CountryModel = apps.get_model("userprofiles", "Country")
    CountryModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("userprofiles", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_initial_data, unload_initial_data),
    ]
