# Generated by Django 4.2.10 on 2024-05-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_auto_20240505_1020'),
    ]

    operations = [
    ]
