# Generated by Django 4.2.10 on 2024-05-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0007_auto_20240505_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='authentication_type',
        ),
    ]
