# Generated by Django 4.2.10 on 2024-05-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0009_alter_userprofile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='userprofiles.interest'),
        ),
    ]
