# Generated by Django 4.2.10 on 2024-05-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0012_alter_userprofile_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
    ]
